<?php
/**
 * Chunked file upload endpoint.
 * Accepts file chunks via POST and assembles them into a complete file.
 *
 * POST params (multipart/form-data):
 *   - chunk: the file chunk (binary)
 *   - chunk_index: 0-based chunk index
 *   - total_chunks: total number of chunks
 *   - upload_id: unique upload session ID (generated by client)
 *   - filename: original filename (sent with every chunk for validation)
 *
 * On final chunk, also accepts:
 *   - name: display name for the image
 *   - default_user: default SSH user
 *   - ostype: OS type (l26, win11, etc.)
 */

require_once __DIR__ . '/../../vendor/autoload.php';

use App\Bootstrap;
use App\Auth;
use App\Request;
use App\Response;
use App\Database;
use App\AppLogger;

Bootstrap::init();
Request::requireMethod('POST');
Request::validateCsrf();

$user = Auth::requirePermission('template.deploy');

$imagesDir = realpath(__DIR__ . '/../../data/images');
if (!$imagesDir || !is_dir($imagesDir)) {
    @mkdir(__DIR__ . '/../../data/images', 0750, true);
    $imagesDir = realpath(__DIR__ . '/../../data/images');
}

$tmpDir = sys_get_temp_dir() . '/pve_uploads';
if (!is_dir($tmpDir)) {
    @mkdir($tmpDir, 0750, true);
}

// Read chunk parameters
$chunkIndex  = (int)($_POST['chunk_index'] ?? -1);
$totalChunks = (int)($_POST['total_chunks'] ?? 0);
$uploadId    = preg_replace('/[^a-zA-Z0-9_\-]/', '', $_POST['upload_id'] ?? '');
$filename    = $_POST['filename'] ?? '';

if ($chunkIndex < 0 || $totalChunks < 1 || !$uploadId || !$filename) {
    Response::error('Missing chunk parameters', 400);
}

// Sanitize filename
$safeName = preg_replace('/[^a-zA-Z0-9._\-]/', '_', basename($filename));
if (!preg_match('/\.(qcow2|img|raw|iso|vhd|vhdx)$/i', $safeName)) {
    Response::error('Unsupported file type', 400);
}

// Check for uploaded chunk data
if (empty($_FILES['chunk']) || $_FILES['chunk']['error'] !== UPLOAD_ERR_OK) {
    $errorCode = $_FILES['chunk']['error'] ?? -1;
    Response::error("Chunk upload failed (error $errorCode)", 400);
}

// Write chunk to temp file (append mode)
$tmpFile = $tmpDir . '/' . $uploadId . '_' . $safeName;
$chunkData = file_get_contents($_FILES['chunk']['tmp_name']);
if ($chunkData === false) {
    Response::error('Failed to read chunk data', 500);
}

// For first chunk, create new file; for subsequent, append
if ($chunkIndex === 0) {
    file_put_contents($tmpFile, $chunkData, LOCK_EX);
    AppLogger::debug('deploy', 'Chunked upload started', [
        'upload_id' => $uploadId, 'filename' => $safeName,
        'total_chunks' => $totalChunks, 'chunk_size' => strlen($chunkData),
    ], $user['id']);
} else {
    file_put_contents($tmpFile, $chunkData, FILE_APPEND | LOCK_EX);
}

// Not the last chunk yet — acknowledge and wait for more
if ($chunkIndex < $totalChunks - 1) {
    Response::success(['chunk_index' => $chunkIndex, 'status' => 'received']);
}

// ── Last chunk: finalize the upload ──
$dest = $imagesDir . '/' . $safeName;
if (file_exists($dest)) {
    @unlink($tmpFile);
    Response::error("File '{$safeName}' already exists", 409);
}

if (!rename($tmpFile, $dest)) {
    @unlink($tmpFile);
    AppLogger::error('deploy', 'Failed to move assembled upload', ['filename' => $safeName], $user['id']);
    Response::error('Failed to save uploaded file', 500);
}

// Register in database
$name        = $_POST['name'] ?? pathinfo($safeName, PATHINFO_FILENAME);
$defaultUser = $_POST['default_user'] ?? 'user';
$ostype      = $_POST['ostype'] ?? 'l26';

$db = Database::connection();
$stmt = $db->prepare('INSERT INTO custom_images (name, filename, default_user, ostype, uploaded_by) VALUES (?, ?, ?, ?, ?) RETURNING id');
$stmt->execute([$name, $safeName, $defaultUser, $ostype, $user['id']]);
$newId = $stmt->fetchColumn();

AppLogger::info('deploy', 'Custom image uploaded via chunked upload', [
    'id' => $newId, 'filename' => $safeName, 'name' => $name,
    'total_chunks' => $totalChunks, 'file_size' => filesize($dest),
], $user['id']);

Response::success(['id' => $newId, 'filename' => $safeName]);
